name: build
on:
 push:
 pull_request:
 schedule:
    # Once a month on the 3rd day at midnight
    - cron: "0 0 3 * *"

jobs:  
    python-tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: |
              sudo apt-get update -y
              sudo apt-get install -y python3-numpy
        - name: Run python unit tests
          run: |
              cd python
              python3 -m hfile
